Ignore offline APIs
We already ignored APIs replying with a non-200 code. Also ignore APIs
not replying at all, e.g.

    requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5003): Max retries exceeded with url: /query/api-meta.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff03151eee0>: Failed to establish a new connection: [Errno 111] Connection refused'))